### ISSUE TITLE
PR#27 breaks the semantics of setproperty!! (not consistent with Base)

### ISSUE THREAD

**Issue by colinxs** [tkf/BangBang.jl#120]
Currently, the following definitions exists:

```julia
possible(::typeof(setproperties!), obj, patch) =
    implements(setproperty!, obj) && _is_compatible_field_types(obj, patch)
_is_compatible_field_types(::T, patch) where T =
    all(n -> fieldtype(typeof(patch), n) <: fieldtype(T, n), keys(patch))
@generated function _is_compatible_field_types(obj, patch::NamedTuple{pnames}) where pnames
    all(n -> fieldtype(patch, n) <: fieldtype(obj, n), pnames)
end
```
which in inconsistent with the definition of Base's `setproperty!`:
```
setproperty!(x, f::Symbol, v) = setfield!(x, f, convert(fieldtype(typeof(x), f), v))
```
and  leads to following problem:
```
mutable struct Foo
x::Int
end

f1 = Foo(1)
f2 = Foo(1)
f1.x = 2.0
BangBang.setproperty!!(f2, :x, 2.0) # creates a new Foo
f1.x == 2 # true
f2.x == 2 # false
```

I see this changed in #27. I'm curious why the check for mutability was insufficient?

**Comment by colinxs** [comment]
changed the title because this appears to have been introduced in the 0.3.2 release

**Comment by tkf** [comment]
> inconsistent with the definition of Base's `setproperty!`

This is kind of a point of BangBang.jl. See:

```julia
julia> using BangBang

julia> setindex!([0], 1.0, 1)
1-element Array{Int64,1}:
 1

julia> setindex!!([0], 1.0, 1)
1-element Array{Float64,1}:
 1.0
```

The latter cannot invoke `convert` as otherwise it's impossible to make "type-widening" path of `setindex!` type-stable.

If you were depending on the semantics of `setproperties!!` before #27, I'm sorry; I shouuld have bumped the leading version. I was regarding #27 as a bug fix as it made `setproperties!!` compatible with everything else in BangBang.jl.

If you want pre-#27 behavior, I'm afraid you'd need to create a new lens based on https://github.com/jw3126/Setfield.jl/pull/95.

**Comment by colinxs** [comment]
I see. Thanks for the quick response! No worries about the version change, it didn't take _too_ long to figure out :) I'll go head and make another lens then! Feel free to close this.
